services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    stop_signal: SIGINT
    stop_grace_period: 30s

  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret123
    stop_signal: SIGINT
    stop_grace_period: 30s

  mail:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    stop_signal: SIGINT
    stop_grace_period: 30s
